### ISSUE TITLE
Scrollable paper-tabs not scrolling when swiping on iOS

### ISSUE THREAD

**Issue by KyleHorkley** [PolymerElements/paper-tabs#101]
When swiping to scroll on iOS with paper tabs and scrollable set to true, it won't work. The only way I can get it to scroll is by using the buttons. I'm on iOS 9.

**Comment by bicknellr** [comment]
[This seems to be fixed in master.](http://jsbin.com/penepa/edit?html,output) I still haven't been able to track down the exact commit.

**Comment by KyleHorkley** [comment]
Let me know if you find out :D

– Kyle Horkley, web designer, kylehorkley.com
On Wed, Dec 16, 2015 at 6:04 PM, PolymerElements/paper-tabs
<reply@reply.github.com>
wrote:
This seems to be fixed in master. [http://jsbin.com/penepa/edit?html,output] I still haven't been able to track down the exact commit.

—
Reply to this email directly or view it on GitHub
[https://github.com/PolymerElements/paper-tabs/issues/101#issuecomment-165305033] .[https://github.com/notifications/beacon/AMWw5WrHOjvJ1uA4C4oy45RictEepY1Lks5pQgGsgaJpZM4Gr23y.gif]

**Comment by bicknellr** [comment]
Closing since this seems fixed.
