### ISSUE TITLE
README incomplete

### ISSUE THREAD

**Issue by KyleHorkley** [PolymerElements/paper-tabs#110]
At the very bottom of the paper-tabs section in the README, it says:

    <style is="custom-style">
        .link {

And then abruptly stops.

**Comment by notwaldorf** [comment]
Innnnnnteresting. @garlicnation, I think this might be a hydrolysis bug? I first suspected it's marked element, but i tried it separately and it seemed to render fine

**Comment by tonlie** [comment]
It's not really missing, paper-tabs.html still contains the info, but the @ chars in the lines 63+64 seem to break the doc.
I couldn't find a way to escape them properly, but tested it with a leading dash with which it creates the complete doc. e.g.:
```
63: -@apply(--layout-horizontal);
64: -@apply(--layout-center-center);
```
I've also had a look at the official JSDoc documentation as well as at [polymers style guide](http://polymerelements.github.io/style-guide/), but did not anything that helped.
I think that *@keyword* is reserved in JSDoc.

**Comment by bicknellr** [comment]
Looks like this is a known issue: https://github.com/Polymer/hydrolysis/issues/139.
