### ISSUE TITLE
Docs are prematurely cut off

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-tabs#117]
<img width="790" alt="screen shot 2015-12-31 at 5 38 22 pm" src="https://cloud.githubusercontent.com/assets/238208/12069116/532b15fe-afe5-11e5-99d4-a94bf685efb3.png">

**Comment by KyleHorkley** [comment]
https://github.com/PolymerElements/paper-tabs/issues/110

**Comment by bicknellr** [comment]
Yeah, this seems to be a known issue outside of paper-tabs: https://github.com/Polymer/hydrolysis/issues/139.
