### ISSUE TITLE
on-selected-changed event fired twice

### ISSUE THREAD

**Issue by ioantomulesei** [PolymerElements/paper-tabs#124]
Hello,

on-selected-changed event is fired twice when added to paper-tabs component. This seems to be caused by the fact that "selected" property is added in paper-tabs component even if is already defined in  Polymer.IronSelectableBehavior(this is a indirect behavior) and this seems to cause two property  effects to be added (for each of the "selected" property) when defining a event handler for on-selected-changed event.
If I remove "selected" property  from paper-tabs component, event is fired once.

Is this behavior desired (event fired twice), for me is not :)

here is the issue: https://jsfiddle.net/ioantomulesei/agrsx8pq/

**Comment by bicknellr** [comment]
p0 since this has a PR in flight.
