### ISSUE TITLE
paper-tabs scrollable inside paper-toolbar does not work

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [PolymerElements/paper-tabs#130]
Hi there!

When setting **scrollable** for a paper-tabs inside a paper-toolbar, makes the paper-tab's disappear.

This does not work:
```html
<paper-header-panel>
    <paper-toolbar justify="center">
        <paper-tabs selected="0" scrollable noink>
            <paper-tab>Home</paper-tab>
            <paper-tab>Quem somos</paper-tab>
            <paper-tab>Produtos</paper-tab>
            <paper-tab>Orçamento</paper-tab>
            <paper-tab>Portfólio</paper-tab>
            <paper-tab>Depoimentos</paper-tab>
            <paper-tab>Contato</paper-tab>
        </paper-tabs>
    </paper-toolbar>
    <div class="home"></div>
</paper-header-panel>
```
![fail](https://cloud.githubusercontent.com/assets/12160864/12659751/94df5cbc-c5f7-11e5-82db-2b4f8304b75f.png)

But this works:
```html
<paper-header-panel>
    <paper-toolbar justify="center">
        <paper-tabs selected="0" noink>
            <paper-tab>Home</paper-tab>
            <paper-tab>Quem somos</paper-tab>
            <paper-tab>Produtos</paper-tab>
            <paper-tab>Orçamento</paper-tab>
            <paper-tab>Portfólio</paper-tab>
            <paper-tab>Depoimentos</paper-tab>
            <paper-tab>Contato</paper-tab>
        </paper-tabs>
    </paper-toolbar>
    <div class="home"></div>
</paper-header-panel>
```
![ok](https://cloud.githubusercontent.com/assets/12160864/12659760/a583d2fa-c5f7-11e5-9a55-df3b768c181b.png)

And if I put the paper-tabs in the header content area, it works as well:

![outside](https://cloud.githubusercontent.com/assets/12160864/12659788/cd751512-c5f7-11e5-9d74-4c71844ad001.png)

The problem is paper-tabs inside paper-toolbar.

Here is the [jsbin](http://jsbin.com/motizam/edit?html,output) that simulate this problem.

**Comment by bicknellr** [comment]
Looks like there's a bit of flex-within-flex fighting going on here.

**Comment by rafael-renan-pacheco** [comment]
![f87](https://cloud.githubusercontent.com/assets/12160864/12673120/e809ad88-c661-11e5-89ab-e87b73bc64eb.jpg)

**Comment by WoodyWoodsta** [comment]
I'm having the same issue, except the behavior can be replicated by placing the `paper-tabs` in any flexbox by the `@apply(--layout-horizontal)` and `@apply(--layout-vertical)` mixins (have not tested the class equivalents, but I expect the same thing)

**Comment by samuelli** [comment]
One workaround is to use `@apply(--layout-flex)` on the `paper-tabs` element: http://jsbin.com/zorogewicu/edit?html,output

**Comment by bicknellr** [comment]
Thanks for the workaround, @samuelli! I think the #165 inadvertently fixed this also. [Here's a demo](http://jsbin.com/qobesi/1/edit?html,output) where adding `flex: 1;` does the trick. I think this is sufficient to close this bug, but if I'm missing a better option please let me know!

**Comment by Brozerker** [comment]
Hey all,
So I'm having this exact same problem except I'm trying to put the paper-tabs inside a paper-dialog instead of a toolbar, and the flex: 1; trick isn't working for it. Any ideas?
