### ISSUE TITLE
Link in description results in 404

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerElements/paper-tabs#131]
The link in the description (https://elements.polymer-project.org/elements/paper-tabs?view=demo:demo/index.html&active=paper-tabs) results in a 404 on the element catalog.

**Comment by bicknellr** [comment]
Yeah, this problem has been sitting around for a bit: #23. :/ A PR to fix it (#128) is merged now but hasn't made it to the catalog yet.

**Comment by TimvdLippe** [comment]
@bicknellr I meant this link on the github repository

![image](https://cloud.githubusercontent.com/assets/5948271/12730216/3ec62612-c92b-11e5-91c8-c649d8f4995f.png)

but I can confirm it is working properly now. Thanks for fixing!

**Comment by bicknellr** [comment]
Oh! I thought you were talking about the fragment link in the docs. I haven't noticed any other issues / PRs about it showing up recently. Thanks for keeping an eye out, let us know if you run into the problem again.

**Comment by bicknellr** [comment]
(PolymerElements/paper-toolbar#79 is similar).
