### ISSUE TITLE
Link inside Tabs doesn't fill the entire tab

### ISSUE THREAD

**Issue by ozasadnyy** [PolymerElements/paper-tabs#135]
The inside link `paper-tab` doesn't fill the entire tab.

## Expected outcome

The same result as I click on the link itself.

## Actual outcome

When I click on the enges of the tab it doen't trigger link inside.

## Steps to reproduce

1. Put a `paper-tabs` element in the page.
2. Put a `<a>` inside `paper-tab` element.
3. Open the page in a web browser.
3. Click on the edge of `paper-tab` element.

`paper-tabs` v.1.3.3

Demo: https://jsbin.com/zezareboro/edit?html,output

![paper-tabs](https://cloud.githubusercontent.com/assets/2954281/13056200/86ae7c4e-d41c-11e5-97a2-6874cce1904e.png)

btw, `height: 100%` of `<a>` helps
![paper-tabs-1](https://cloud.githubusercontent.com/assets/2954281/13056299/33823a50-d41d-11e5-8031-19998c44a478.png)

**Comment by bicknellr** [comment]
Hmm, looks like we have `height: 100%` already: https://github.com/PolymerElements/paper-tabs/blob/3d03528/paper-tab.html#L100. Maybe we finally phased out `::content`?

**Comment by robdodson** [comment]
We need this for the I/O site. Is it possible to prioritize it?

**Comment by bicknellr** [comment]
Haha: #136!
