### ISSUE TITLE
If paper-tabs doesn't contain a paper-tab it becomes a keyboard trap

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/paper-tabs#137]
See https://github.com/PolymerElements/iron-menu-behavior/issues/50

**Comment by bicknellr** [comment]
(btw, PR: PolymerElements/iron-menu-behavior#51 for that bug)

**Comment by robdodson** [comment]
\o/

**Comment by bicknellr** [comment]
I'm going to close this issue since PolymerElements/iron-menu-behavior#50 is the real culprit.
