### ISSUE TITLE
tab[link]: keyboard selection doesn't click anchor tag

### ISSUE THREAD

**Issue by robrez** [PolymerElements/paper-tabs#141]
When using anchor tags as a paper-tab, tab-selection via keyboard input does not click the link:

```
<paper-tabs>
  <paper-tab link><a href="#one">One</a></paper-tab>
  <paper-tab link><a href="#two">Two</a></paper-tab>
  <paper-tab link><a href="#three">Three</a></paper-tab>
</paper-tabs>
```

I wasn't sure, given all of the behaviors involved in `paper-tabs` and `paper-tab` what a "correct" fix would be. `iron-button-state` calls `click()` on a tab after space or enter is keyed into a focused tab. Playing around w/ paper-tab (_in a way that I'm sure is wrong_), the following "works":
```
      listeners: {
        down: '_updateNoink',
+       click: '_onClick'
      }
...
      _onClick: function(e) {
        if (this.hasAttribute("link")) {
          var link = this.getEffectiveChildren("a");
          if (link && link.length) {
            link[0].click();  //potential loop?
          }
        }
      }
```

**Comment by bicknellr** [comment]
Actually, that sounds like a pretty valid solution to me.

**Comment by robdodson** [comment]
+100000000

Running into this on the  I/O site and it's super frustrating.

**Comment by abdonrd** [comment]
Reference about anchors: https://github.com/PolymerElements/iron-elements/issues/37
