### ISSUE TITLE
 Paper tabs keep on shaking when clicking multiple times on paper-icon-button

### ISSUE THREAD

**Issue by developerajendra** [PolymerElements/paper-tabs#144]
Steps to reproduce:
When you click on paper-icon-button next(<) and previous(>) multiple time, tabs start shaking. 

See attached video for details : https://vid.me/iyFi

**Comment by bicknellr** [comment]
Hi @developerajendra, could you provide a reproable test case? Is the small width of the tabs (as shown in your video) necessary to repro? Any other info?

**Comment by bicknellr** [comment]
Let me know if you've got any more details / a test case reproducing this issue and I can reopen.

**Comment by developerajendra** [comment]
I couldn't found issue now I guess that is solved somehow, sure I will let you know if I will get anything in future.
