### ISSUE TITLE
paper-tabs does not work properly inside neon-animated-pages

### ISSUE THREAD

**Issue by fenerlee1907** [PolymerElements/paper-tabs#152]
### Description
Recently I try to upgrade our project from Polymer 1.2.1 to Polymer 1.4.0 with all other components. During this process, I upgraded paper-tabs from 1.0.10 to 1.5.0 and neon-animation from 1.0.8 to 1.2.0.

After I upgraded all, there is a strange issue came out. I cannot use paper-tabs inside neon-animated pages. When I use paper-tabs all alone, everything is normal. But when I put it inside neon-animated-pages, paper-tabs' tab change event also triggers something in neon-animated pages. As result, paper-tabs try to animate whole page instead of tab contents. If I try to change tabs, tab content is gone!

I think, fiddle explains this all more clearly. I also put a video to show that changing tab triggers something in neon-animated-pages.

Any help will be appreciated, thanks.

### Expected outcome

paper-tabs has to work properly in neon-animated-pages as it works alone

### Actual outcome

Changing tabs triggers strange animations and causes tab content disappear

### Live Demo
https://jsfiddle.net/q91rn6b1/4/
http://tinypic.com/player.php?v=2zyesyc&s=9#.Vwyx0xjTS_E

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by fenerlee1907** [comment]
I think the problem is more complicated than just a paper-tabs issue. When An element inside neon-animated pages triggers iron-select event, it also triggers iron-select event of neon-animated-pages. When I select a tab, this triggers iron-select event of neon-animated pages.

Problem is very strange. There is another related issue under neon-animation page. 

https://github.com/PolymerElements/neon-animation/issues/164

**Comment by vguillou** [comment]
This is indeed a problem with neon-animated-pages, that as already been [reported].(https://github.com/PolymerElements/neon-animation/issues/146)
I think you should probably close this issue.

**Comment by fenerlee1907** [comment]
Thanks @vguillou . 

References to other issues:

https://github.com/PolymerElements/neon-animation/issues/146
https://github.com/PolymerElements/neon-animation/issues/164
