### ISSUE TITLE
Arrow is showing even when it shouldn't

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-tabs#16]
For `scrollable` tabs the arrows should only be shown when there is more tabs to show.

In the following example, the `<` next to `NUMBER ONE ITEM` should not be shown.
![screen shot 2015-05-21 at 2 55 02 pm](https://cloud.githubusercontent.com/assets/116360/7759817/a324c252-ffc9-11e4-95b9-9c92346fa71b.png)

**Comment by dman777** [comment]
Err.... with version 1.8 I am having a issue their opacity is 0 100% of the time.
