### ISSUE TITLE
Scroll issue when creating tabs dynamically

### ISSUE THREAD

**Issue by MartinMoizard** [PolymerElements/paper-tabs#160]
There is a scroll issue when tabs are created programatically. When scrolling, the browser always makes sure the selected tab is visible, so when the selected tab disappears (because the user scrolls), the scroll "jumps" and the selected tab is visible again.

Can be reproduced here: https://jsfiddle.net/2q3fqehz/37/ 
It is not possible to scroll (doing a click&drag, not with the side buttons) to "Tab num 15" for example.

It can be fixed by initializing the tabIndex to -1 when creating the paper-tab items: https://jsfiddle.net/2q3fqehz/38/

Is it expected that we must init the tabIndex to -1 to avoid this kind of issue?

**Comment by bicknellr** [comment]
I can't reproduce the issue on the page you've provided, can you give any more details?

**Comment by MartinMoizard** [comment]
Somehow, it has been fixed.

**Comment by bicknellr** [comment]
Cool; let me know if this shows up again.
