### ISSUE TITLE
Paper-tabs in shadow dom does not show bar on initial load

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerElements/paper-tabs#162]
### Description
Initially paper-tabs does not show the bar, because `tab.getBoundingClientRect()` returns all zeroes. However, later the function correctly returns the width and height of the tab.
Because `getBoundingClientRect()` returns all zeroes, `this._calcPercent(tabRect.width, w)` and `this._calPercent(tabOffsetLeft)` in `_tabChanged` result in `NaN` due to division by zero.

### Expected outcome
The bar is shown on the initial page load.

### Actual outcome
On the initial page load the bar is not shown. When you switch tabs it does show the demo

### Live Demo
This is a bit tricky, as I have been unable to reproduce this problem inside a jsbin but consistenly reproducing in our app. So for now the app https://github.com/preview-code/rite-evaluation shows the behavior.

### Steps to reproduce
1. Clone the above project
* `npm install`
* `bower install`
* `gulp serve`
* Click "Login with Github". This should redirect to `localhost:5200/projects`
* Observe that the tabs above do not show an orange bar
* Click on "Home" or "My pull requests"
* Observe that the orange bar is shown.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

The issue seems to be related to shadow dom, however disabling shadow dom in `index.html` does not resolve the issue. Loading in Firefox with shady dom does not show this behavior.

**Comment by bicknellr** [comment]
P2-ing this since using Shady DOM (Polymer's default anyways) is a sufficient workaround. Also, a reduced test case would be good. :)

**Comment by bicknellr** [comment]
Closin

**Comment by cmevawala** [comment]
+!
