### ISSUE TITLE
Scrollable tabs in large containers

### ISSUE THREAD

**Issue by sparhami** [PolymerElements/paper-tabs#163]
### Description
Using scrollable paper-tabs does not play well with responsive usage since they fail to property expand to take the available space prior to there being enough that they need to scroll.

### Expected outcome
Tabs should expand to fit the container

### Actual outcome
Tabs do not expand to fit the container

### Live Demo
https://jsbin.com/kofamuzemo/edit?html,output

### Steps to reproduce
1. Add a `<paper-tabs scrollable>` element with some `<paper-tab>`s to a page
2. Have  a large enough container that tabs do not need to scroll 

### Browsers Affected
All

**Comment by bicknellr** [comment]
Released as v1.6.0.
