### ISSUE TITLE
selectPrevious always goes to the focussed tab. Not the previous tab.

### ISSUE THREAD

**Issue by sander76** [PolymerElements/paper-tabs#167]
### Description
`selectPrevious()` always goes to the focussed tab. Not the previous tab.

### Expected outcome
Previous tab is selected.

### Actual outcome
Focussed tab is selected.

### Live Demo
Sorry don't know how to do this..

### Steps to reproduce

1. I have keybindings using `iron-a11y-keys` to the `selectNext` and `selectPrevious` method of a paper-tabs.
2. I select a tab using the mouse. When I select a tab using the mouse it gets *focus*. 
3. I then use the keyboard to do a `selectNext` for the next tab *twice*. This works as it should.
4. Now a `selectPrevious` selects the focussed tab. Not the previous tab.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by bicknellr** [comment]
This seems to be working as expected: http://jsbin.com/pamawo/1/edit?html,output . Let me know if you have any more specific details or a test case that reproduces it and I'll reopen.
