### ISSUE TITLE
Add custom property for paper-tab focused and selected style

### ISSUE THREAD

**Issue by bipin-nag** [PolymerElements/paper-tabs#178]
### Description

Please add `--paper-tab-content-focused` or/and `--paper-tab-content-selected`. Also remove `--paper-tab-content-unselected`. It is confusing.
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by rubenlg** [comment]
Plus the focused state is incorrectly implemented. It should not change the font weight according to the material design spec. By doing so, it makes the whole list of tabs move every time the focus changes.

**Comment by bicknellr** [comment]
Fixed in #237.
