### ISSUE TITLE
Can I put an Icon inside a paper-tab, rather than, or in addition to, text?

### ISSUE THREAD

**Issue by rchrdnsh** [PolymerElements/paper-tabs#180]
I would like to be able to put icons inside paper-tabs and wanted to ask if this is possible.

Thanks

**Comment by bicknellr** [comment]
Yup! ([demo here](http://jsbin.com/jehexi/1/edit?html,output) - and no, you don't have to specifically use `iron-icon`) You can put lots of things in a paper-tab but it can get tricky from a styling / interaction perspective sometimes.
