### ISSUE TITLE
Custom tab element inside paper tabs element

### ISSUE THREAD

**Issue by cmevawala** [PolymerElements/paper-tabs#192]
Hi @robdodson , 
I have created element and i have named it as a pebble-tab element which is a wrapper on top of the paper-tab element. Now i want to use pebble-tab in paper-tabs element.Do we have any provision for this scenario.

e.g. `<paper-tabs>
            <pebble-tab></pebble-tab>
            <pebble-tab></pebble-tab>
       <paper-tabs>`

**Comment by robdodson** [comment]
@bicknellr is the owner for paper-tabs and would know more :)

**Comment by bicknellr** [comment]
Hi @cmevawala, [`paper-tabs` selects only `paper-tab`(s) by default](https://github.com/PolymerElements/paper-tabs/blob/196c3efb2c3dd16d158159658618ddd79e12d545/paper-tabs.html#L310) but you can change `selectable` to whatever you'd like. It's a CSS selector that determines which children are considered selectable items which is [inherited from IronSelectableBehavior](https://github.com/PolymerElements/iron-selector/blob/f894fa4239d27d06900497e75f456fa3eaa785cc/iron-selectable.html#L99).
