### ISSUE TITLE
In RTL the arrow appears on the wrong side in non-Chrome

### ISSUE THREAD

**Issue by helenxywu** [PolymerElements/paper-tabs#203]
### Description
In RTL the arrow to navigate tabs appears on the right side when there are more items on the left side.

### Expected outcome
Arrow should appear on the left side when there are items to the left.

### Actual outcome
Arrow appears on the right side.

### Live Demo
https://user-content-dot-custom-elements.appspot.com/PolymerElements/paper-tabs/v1.7.0/paper-tabs/demo/index.html (Use Firefox, Safari, or Edge)

### Browsers Affected
Firefox, Edge, Safari (Chrome works)

**Comment by bicknellr** [comment]
The code needed to do this is basically never going to get merged, so I'm closing this issue as a wontfix.
