### ISSUE TITLE
v2.0.0 not published on webcomponents.org

### ISSUE THREAD

**Issue by andrewspy** [PolymerElements/paper-tabs#215]
### Description
v2.0.0 not published on webcomponents.org

### Expected outcome

published on webcomponents.org

### Actual outcome

latest version on webcomponents.org is v1.8.0

### Live Demo

https://www.webcomponents.org/element/PolymerElements/paper-tabs

**Comment by Fleker** [comment]
It seems like this is no longer applicable as 2.0.0 is the latest version on the website now.

**Comment by notwaldorf** [comment]
Closing, then. Thanks for checking!
