### ISSUE TITLE
Error in Polymer 3

### ISSUE THREAD

**Issue by AnkitMaheshwariIn** [PolymerElements/paper-tabs#226]
**After install and import :**
npm i @ polymer/paper-tabs

import '@ polymer/paper-tabs/paper-tab.js';
import '@ polymer/paper-tabs/paper-tabs.js';

**Getting error on run :**

polymer-fn.js:43 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at Polymer (http://localhost:8081/node_modules/@polymer/polymer/lib/legacy/polymer-fn.js:43:18)
    at http://localhost:8081/node_modules/@polymer/paper-tabs/node_modules/@polymer/paper-ripple/paper-ripple.js:314:1

**Comment by LLLLuca** [comment]
Same problem for me when I try to add paper-tabs via npm 
(using: npm i @polymer/paper-elements or npm i @polymer/paper-tabs)

**Comment by sebs** [comment]
@notwaldorf 
I have this in my lerna repos as 'npm run reset' and it could be  useful in polymer init.

**Comment by notwaldorf** [comment]
Closing, since there haven't been updates and I think my workaround works :)
