### ISSUE TITLE
Fragment links in docs don't do anything

### ISSUE THREAD

**Issue by justinfagnani** [PolymerElements/paper-tabs#23]
See https://github.com/PolymerElements/paper-tabs/blob/master/paper-tabs.html#L36

**Comment by cdata** [comment]
Thanks for reporting. Will take a look.

**Comment by cdata** [comment]
Could you re-open with a clarification of what you expect the fragment links to do? Thanks!

**Comment by justinfagnani** [comment]
Go somewhere? Right now the link just doesn't work, might as well remove it.

**Comment by justinfagnani** [comment]
Considering that the link is to a fragment, there should be a named anchor somewhere, right?

**Comment by notwaldorf** [comment]
@bicknellr would you mind fixing this link to one that works? Thanks so much! :)
