### ISSUE TITLE
any parameter that use camelCase dosen´t work

### ISSUE THREAD

**Issue by iFernandoSousa** [PolymerElements/paper-tabs#26]
After long time trying understand what happen if my paper-tab with parameters hideScrollButtons and scrollable, I found a problem that I think is general for all Polymer Componentes 1.0.

If I rename this param: hideScrollButtons to hidescrollbuttons, without any UpperCase char, this work fine, the problem is same for all parameters that have any uppercase char, some like: disableDrag, noSlide and noBar.

**Comment by morethanreal** [comment]
Camel case properties names are deserialized dash-case in attributes, e.g. `hideScrollButtons` is `hide-scroll-buttons` as an attribute. More info here: https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#attribute-deserialization

**Comment by cdata** [comment]
Yes, @morethanreal is correct. Please re-open if you believe we misunderstood the issue.
