### ISSUE TITLE
Add vertical orientation support

### ISSUE THREAD

**Issue by justinfagnani** [PolymerElements/paper-tabs#30]
Designer has an old fork of tabs modified to layout vertically. It'd be great to merge into one implementation.

**Comment by morethanreal** [comment]
Hmm, is a vertical tab a `<paper-menu>`? Or do you want the ripply tabs? Maybe it's possible to put a `<paper-tab>` in a `<paper-menu>`.

**Comment by robrez** [comment]
I'd love to see this enhancement, too.
It's been requested over in the .5 repo, too...
https://github.com/Polymer/paper-tabs/issues/24

@morethanreal I think we'd miss out on the nifty selectionBar indicator animation if it were just ripply menu items.

**Comment by justinfagnani** [comment]
@cdata did you have some work towards this at one point?

**Comment by notwaldorf** [comment]
I'm closing this since it's not covered by the spec, and it's kind of a weird UX paradigm
