### ISSUE TITLE
Host demo on GH pages?

### ISSUE THREAD

**Issue by techtonik** [PolymerElements/paper-tabs#35]
I'd like to see how it looks like without checking the source out. Is that possible?

**Comment by notwaldorf** [comment]
All elements live in an elements [catalog](https://elements.polymer-project.org). The paper-tabs demo is [here](https://elements.polymer-project.org/elements/paper-tabs?active=paper-tabs&view=demo:demo/index.html). :tada:

**Comment by techtonik** [comment]
@notwaldorf cool. =) How about linking [that](https://elements.polymer-project.org/elements/paper-tabs?active=paper-tabs&view=demo:demo/index.html) in GitHub project header?

**Comment by notwaldorf** [comment]
We're working on it! (All the elements would benefit from it, so we're trying to automate it somehow)

**Comment by techtonik** [comment]
BTW, are there any galleries to submit your own element with that pretty docs and examples?

**Comment by notwaldorf** [comment]
@techtonik Not at the moment. We are working on a solution for that :)
(the catalog, however, is open source if you want to play around with it: https://github.com/Polymer/polymer-element-catalog)

**Comment by techtonik** [comment]
=) One last question if you don't mind - what editor do you use to work with Polymer components? I mean not only developing the components themselves, but also using them to create pages conveniently. My current method is a plain editor, which is not effective.

**Comment by notwaldorf** [comment]
@techtonik I use Atom for everything (a lot of people also use Sublime Text). We don't use any fancy IDEs :)
