### ISSUE TITLE
Add a variable for styling the selected tab color.

### ISSUE THREAD

**Issue by skidgel** [PolymerElements/paper-tabs#36]
It would be nice if there was a simpler way to style the selected tab's text color. In the Material Design spec they recommend that the text color should match the selection bar for the light theme:

![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsVDk4V2Nnc2U3LTQ/components_tabs_usage_mobile4.png)

Perhaps there could be a --paper-tab-selected-color or --paper-tab-selected-text-color? 

At the moment, I'm trying to style it like:
```
.iron-selected {
  --paper-tab {
    color: #4184f3;
  };
}
```

But that doesn't work. What did work was using /deep/ but that is an expensive option :-/

```
  body /deep/ paper-tab.iron-selected {
    color: #4184f3;
  }
```

**Comment by robrez** [comment]
Does something like this work for you?
```
<style is="custom-style">
paper-tabs {
  color: blue;
  --paper-tabs-selection-bar-color: blue;
}
</style>
```

**Comment by skidgel** [comment]
That does work, but it styles all tab text to be blue. I only want the selected tab to be blue. Make sense?

**Comment by robrez** [comment]
Yeah I follow you now.

Not that this gives you what you're looking for -- but, I do think you could avoid the /deep/ selector if you imported the custom style in whichever contexts you needed it...

ie: tab-theme.html:
<style is="custom-style">
paper-tabs {
  --paper-tabs-selection-bar-color: blue;
}
paper-tab {
  color: #212121;
}
paper-tab.iron-selected {
  color: blue;
}
</style>

Arthur Evans has a good comment on this approach:
https://github.com/Polymer/docs/issues/1208#issuecomment-113331547

Rob Dodson has a polycast episode on theming that touches on it here:
https://youtu.be/omASiF85JzI?t=589

**Comment by cdata** [comment]
@skidgel 
@robrez 's approach should work. If it doesn't please re-open the issue and we can discuss.

**Comment by yglodt** [comment]
This works for me for setting the selected tab's color and background-color:
```
paper-tab.iron-selected {
	color: #0075b2;
	background-color: green;
}
```
