### ISSUE TITLE
Polymer 1.0.3 Paper-Tabs Are Not Responsive To Content

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-tabs#37]
_From @dman777 on June 19, 2015 0:48_

Using Polymer 1.0, the paper-tab elements are not responsive to the size of their content/titles. Instead, all the tabs are a fixed size and it looks bad. From what I can tell, the default behavior is for them to be responsive to their contents. Can anyone clarify this please? Is this a bug?

```html
<!doctype html>
<html>

<head>

  <title>unquote</title>

  <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">

  <script src="bower_components/webcomponentsjs/webcomponents.js"></script>

  <link rel="import" href="bower_components/paper-header-panel/paper-header-panel.html">
  <link rel="import" href="bower_components/paper-tabs/paper-tabs.html">
  <link rel="import" href="bower_components/paper-toolbar/paper-toolbar.html">
  <link rel="import" href="bower_components/iron-flex-layout/iron-flex-layout.html">
</head>
<body>
  <paper-header-panel>
    <paper-toolbar>
        <paper-tabs>
          <paper-tab>
              ABOUT
          </paper-tab>
          <paper-tab>
            <div>
              TOUR SCHEDULE
            </div>
          </paper-tab>
            <paper-tab>
              <div>
                VIDEOS
              </div>
            </paper-tab>
            <paper-tab>
              <div>
                HOST
              </div>
            </paper-tab>
            <paper-tab>
              <div>
                LONG TITLE THIS IS
              </div>
            </paper-tab>
        </paper-tabs>
    </paper-toolbar>
  </paper-header-panel>
</body>
</html>
```

![pic1](https://cloud.githubusercontent.com/assets/887815/8245343/ad362224-15f2-11e5-8398-8a75e3cdae6a.jpg)

_Copied from original issue: Polymer/polymer#1914_

**Comment by dman777** [comment]
Found out I needed to use ` <paper-tabs  class='flex'>` instead of ` <paper-tabs  flex>`. Where can I read about the proper layout for version 1.0? Iron flex element doc is empty.

**Comment by notwaldorf** [comment]
Layout attributes have been replaced by custom properties or classes. Here are some details from the migration guide (https://www.polymer-project.org/1.0/docs/migration.html#layout-attributes), and a nice explanation from @arthurevans: https://github.com/Polymer/docs/issues/1208#issuecomment-113331547

**Comment by domenicop** [comment]
Using `<paper-tabs class='flex'>` only enlarges the tabs, it does not distribute their width according to the content. Please re-open this issue, as it's still not fixed!

**Comment by dman777** [comment]
You  are correct. I hadn't spent enough time with it before....still same issue. @tjsavage or @notwaldorf, please reopen this issue.

**Comment by sjmiles** [comment]
If you want the tabs to fit to their content, you can override the default tab flexing:

```
<style is="custom-style">
  paper-tab {
    flex: none;
  }
</style>
```

http://jsbin.com/bizoso/edit?html,output

**Comment by arthurevans** [comment]
By the way, I don't think anyone answered the original question here, which was, "Is this a bug?" The answer I believe is No.  These tabs are designed to implement the material design guidelines, and those guidelines explicitly say:

- When choosing a text label, use short titles.
- Do not resize labels. If labels are too long, use scrollable tabs instead, or wrap text to a second line.

**Comment by dman777** [comment]
@arthurevans, Interesting.... I am little confused, though, if you could please clarify:

> Do not resize labels. If labels are too long, use scrollable tabs instead, or wrap text to a second line.

 Not re-sizing labels means all tabs are the same fixed size, correct? I have found this to way to look odd with tabs all the same fixed size. In addition, I use https://events.google.com/io2015/ as a example to go by(which I think looks really good) and it's tabs are sized according to the label.

**Comment by arthurevans** [comment]
Hmm... You're right. Perhaps I'm misinterpreting the spec here and it's not intended to be that strict.

Maybe @zgibson can point us right.

**Comment by dman777** [comment]
Hi, I upgraded all my elements and this issue came back. It's been a long time so I can not remember what I did to to force the labels not to re-size...but whatever I did in the past isn't working now because they are re-sizing after the upgrade.
