### ISSUE TITLE
docs: "To use links in tabs" doesn't explain why or what links do.

### ISSUE THREAD

**Issue by justinfagnani** [PolymerElements/paper-tabs#38]
What does the `link` attribute for `paper-tab` do? Why would I want to use it?

**Comment by hourliert** [comment]
Hi,

It removes the padding of the `paper-tab` element. [Cf](https://github.com/PolymerElements/paper-tabs/blob/master/paper-tab.html#L63).

If you don't use this attribute and click in the padded pixels of `paper-tab`, the link will not work.

Hope it answers your question.
Thomas

**Comment by justinfagnani** [comment]
Was there some resolution to this other than just closing the bug? The docs still don't explain what the attribute does. Integrating the explanation from @hourliert would be a good start.
