### ISSUE TITLE
How to make ripples to go all the way?

### ISSUE THREAD

**Issue by rahul-desai3** [PolymerElements/paper-tabs#42]
When someone clicks on any of the tabs, I want to give the ripple effect just like the nav on this page: https://newslab.withgoogle.com/experiments

Please point me in the right direction.

**Comment by GrahenKraken** [comment]
Try using a `<paper-ripple>` element on the container, and `noink` on the tabs. That way your ripple is separated from the tabs and you can customize it as you wish.

**Comment by rahul-desai3** [comment]
It didnt work for me. 

I added `<paper-ripple>` as container and tried `noink` on both `<paper-tabs>` and `<paper-tab>`.

Here is my relevant part of code:  https://gist.github.com/rahul-desai3/d29c8381e5fe13ef2602

**Comment by GrahenKraken** [comment]
`<paper-ripple>` works from INSIDE the parent container, like:

```html
<div id="container">
    <paper-ripple></paper-ripple>
    <paper-tabs> ... </paper-tabs>
</div>
```

**Comment by rahul-desai3** [comment]
Works just as expected. Thank you so much!

**Comment by GrahenKraken** [comment]
No problem :)

**Comment by cdata** [comment]
@GrahenKraken thanks for the tutorial. Your advice was perfect. Closing this issue.
