### ISSUE TITLE
Right chevron not displayed when paper-tabs are hidden on creation then displayed after click

### ISSUE THREAD

**Issue by antitheos** [PolymerElements/paper-tabs#45]
Take following example

    <div style="display:hidden">
        <paper-tabs scrollable="true">
            <paper-tab>TAB 1</paper-tab>
            <paper-tab>TAB 2</paper-tab>
            <paper-tab>TAB 3</paper-tab>
        </paper-tabs>
    <div>

When this is the paper-tabs is initialized it calls a method `_scroll` which sets ups properties to control if the chevrons should appear.  It decides to show the right chevron based on the code below

    scrollLeft = this.$.tabsContainer.scrollLeft;
    this._leftHidden = scrollLeft === 0;
    this._rightHidden = scrollLeft === this._tabContainerScrollSize;

however because the parent is hidden `this._tabContainerScrollSize` evaluates to zero and so the right chevron is marked as hidden.  When the tab bars are later displayed, by tapping a button and running code, the chevron remains hidden because the `_scroll` method is not call again.

I worked around the issue by setting my parent div to have a height of zero and hiding the over scroll. I make the tabs visible by changing the height.

Additionally item to note is that the right chevron is still there and can interacted with even though it is missing from the screen.  This is because the code is using opacity to hide the chevron.

**Comment by cdata** [comment]
Is it possible that this is related to #70 ? I'm going to close this as a dupe just in case. Please re-open it if you think it is not a dupe.
