### ISSUE TITLE
On scrollable tabs, right chevron does not disappear when reaching end of tabs, possibly due to rounding errors

### ISSUE THREAD

**Issue by antitheos** [PolymerElements/paper-tabs#46]
I have set up a paper-tabs instance that came to following dimensions by looking chrome inspector:

   #tabsContainer width = 232
   #tabsContent width =  408.719

the method `_scroll` is responsible for deciding to show the right chevron based on the following code

    scrollLeft = this.$.tabsContainer.scrollLeft;
    ...
     this._rightHidden = scrollLeft === this._tabContainerScrollSize;

`this._tabContainerScrollSize` is calculated in method

    get _tabContainerScrollSize () {
      return Math.max(
        0,
        this.$.tabsContainer.scrollWidth -
          this.$.tabsContainer.offsetWidth
      );
    },

`this.$.tabsContainer.scrollWidth` is supposed to match '#tabsContent width', but it is rounding the value up to 409. This cause problems because the expected content width is now longer than in reality.  When we reach the end of the tabs content we get the following values:

    this.$.tabsContainer.scrollWidth = 409, this should match tabsContent width, which is 408.719
    this.$.tabsContainer.offsetWidth = 232
    this._tabContainerScrollSize = 177

    this.$.tabsContainer.scrollLeft = 176

There is now an extra one pixel we will never be able to scroll, and the right chevron is never hidden

**Comment by cdata** [comment]
Hi, I think that this issue has been resolved. Please re-open if you are still able to reproduce it!
