### ISSUE TITLE
paper-tabs doesn't fully support splicing

### ISSUE THREAD

**Issue by edvail** [PolymerElements/paper-tabs#47]
When array item is removed and another one is added in one splice on model array, paper-tabs just removes removed item from DOM without adding a new one.
Please, take a look at the proof: <a class="jsbin-embed" href="http://jsbin.com/xijipu/embed?html,output">paper-tabs-splicing-problem on jsbin.com</a><script src="http://static.jsbin.com/js/embed.min.js?3.34.1"></script>

**Comment by cdata** [comment]
Hi, this should be fixed as of https://github.com/PolymerElements/iron-selector/pull/73. Please update and re-open this issue if you still see a problem!
