### ISSUE TITLE
Scrollable tabs not working at all on Chrome 45

### ISSUE THREAD

**Issue by David-Mulder** [PolymerElements/paper-tabs#57]
No idea what's happening, but both on my own project and the official demo on elements.polymer-project.org the scrollable tabs will not scroll right when I click them. (It does however work on Firefox.) There is a slight judder going through the tabs *as if* they try to scroll, but no lasting effect. There are no errors on the console and I wasn't able to find where the problem came from at all.

**Comment by David-Mulder** [comment]
And for the record, this is on ChromeOS (Toshiba Chromebook 2, dev mode enabled, but running stable normally), as I was just now reading through the issues and there was weird behaviour on Mac OSX, so just wanted to be explicit enough.

**Comment by David-Mulder** [comment]
And now that I have access to a few more computers: It misbehaves on other Chrome 45 installations on Windows as well.

**Comment by azakus** [comment]
I think I know what this is, and I should be fixed with #59. The buttons are actually on a fast setInterval loop, but the down+up combo may come faster than the first turn of the loop.

**Comment by cdata** [comment]
This appears to be fixed. Please re-open if it is still a problem!
