### ISSUE TITLE
paper-tab is broken on safari browsers

### ISSUE THREAD

**Issue by davidrissato** [PolymerElements/paper-tabs#60]
It throws an error "TypeError: null is not an object (evaluating 'this.parentNode.nodeType')" in Safari 7.1.8 (9537.85.17.9.1) (Mac Desktop), and the same error happens in iOS 8.4 Safari. This error breaks other polymer events (like attached) in other components on the same page, making this component unusable on mentioned browsers.

I tracked down the problem and discovered that it is related to paper-ripple element. This element is inside a ```<template is="dom-if">``` tag, and it apparently receives a null pointer when trying to find its parentNode. (Obs: this occurs only in those browser, this problem never occurred on Chrome or Firefox)

I checked paper-button source code to see how they did solve this problem (that element has a noink property too and it works fine over there). I found that they hide the paper-ripple using a CSS selector instead of a dom-if tag.

If we want to use the same solution in paper-tabs, we can change ```paper-tab.html``` by removing ```<template is="dom-if" ...></template>``` tags and adding an attribute ```noink=[[noink]]``` to the paper-ripple. And finally, we can reflect noink atribute to the host. This way we can control paper-ripple display using CSS. Here are the changes:

```diff
@@ -97,6 +97,10 @@
       -webkit-flex-basis: 0.000000001px;
       flex-basis: 0.000000001px;
     }
+
+    :host[noink] > paper-ripple {
+      display: none;
+    }
   </style>
 
   <template>
@@ -105,9 +109,7 @@
       <content></content>
     </div>
 
-    <template is="dom-if" if="[[!noink]]">
-      <paper-ripple id="ink" initial-opacity="0.95" opacity-decay-velocity="0.98"></paper-ripple>
-    </template>
+    <paper-ripple id="ink" noink="[[noink]]" initial-opacity="0.95" opacity-decay-velocity="0.98"></paper-ripple>
 
   </template>
 
@@ -133,7 +135,8 @@
        */
       noink: {
         type: Boolean,
-        value: false
+        value: false,
+        reflectToAttribute: true
       }
 
     },
```

PS: I checked the paper-ripple object and it suppresses pointer-events when it has a noink attribute correctly configured.

**Comment by cdata** [comment]
Thanks for reporting and for doing that research.

I think it's time that we make `paper-tab` use the relatively new `PaperRippleBehavior`.
