### ISSUE TITLE
Paper-Tabs inside (paper-scroll-header-panel) with scrollable option not rendering !

### ISSUE THREAD

**Issue by emersonbottero** [PolymerElements/paper-tabs#64]
to test use PSK 1.0.3 and replace 
   <div class="bottom-title paper-font-subhead">The future of the web today</div>
with

  <paper-tabs class="bottom-title paper-font-subhead" selected="0" noink scrollable>
                                 <paper-tab>Show</paper-tab>
                 <paper-tab>Eventos</paper-tab>
                 <paper-tab>Teatro</paper-tab>
                 <paper-tab>Festivais</paper-tab>
                 <paper-tab>Festas</paper-tab>
                 <paper-tab>Especiais</paper-tab>
                 <paper-tab>schwarzenegger</paper-tab>
   </paper-tabs>

**Comment by cdata** [comment]
Hi, unfortunately this issue does not contain sufficient information to describe the problem. Please re-open with a clear description of what is happening, what you expected to happen, and steps to reproduce. If possible include a test case as well.
