### ISSUE TITLE
Scrollable tabs focus issue with shadow DOM

### ISSUE THREAD

**Issue by eliseosoto** [PolymerElements/paper-tabs#65]
1. Go to the paper-tabs demo page and force the shadow DOM (https://elements.polymer-project.org/bower_components/paper-tabs/demo/index.html?dom=shadow)
2. In example (E) click any scroll button.
3. The scroll button loses focus and the focus goes to the paper-tabs's selectedItem.

This is a problem because it causes a weird effect where the horizontal scroll jumps back to the selected item briefly, this is specially noticeable with fast clicks on the scroll button.

NOTE: This WAI with shadow DOM turned off.

**Comment by cdata** [comment]
Thanks for the detailed report!

**Comment by bicknellr** [comment]
PR #65 should handle this.
