### ISSUE TITLE
attrForSelected not implemented

### ISSUE THREAD

**Issue by amitmerin** [PolymerElements/paper-tabs#69]
Although documentation states: "If you want to use the attribute value of an element for selected instead of the index, set this to the name of the attribute." there is no implementation of this attribute, nor is there a reference to a behavior implementing this attribute

**Comment by emersonbottero** [comment]
this work for me

``` html
<paper-tabs id="pt" selected="{{selectedtab}}" scrollable align-bottom noink on-iron-select="_onTabselect" attr-for-selected="name">
                <paper-tab name="*">Todos</paper-tab>
                <template is="dom-repeat" items="[[tabs]]" as="categoria">  
                  <paper-tab name="[[categoria.name]]">[[categoria.name]]</paper-tab>
               </template>
            </paper-tabs>
```

then I can do something like

``` html
      ready: function(){
        this.$.pt.selected = '*';
      },
´´´

**Comment by cdata** [comment]
Hi. This is implemented in a behavior here: https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L48-L55
