### ISSUE TITLE
paper-tab::_flattenBehaviorsList]: behavior is null

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-tabs#86]
When upgrading to 1.0.10 I get breakage with `paper-tab::_flattenBehaviorsList]: behavior is null, check for missing or 404 import`. 

###### Update: 
This issue started at 1.0.9

**Comment by bicknellr** [comment]
Dependencies changed between 1.0.8 and 1.0.9. Did you run `bower update`?

**Comment by dman777** [comment]
No, it didn't.

**Comment by bicknellr** [comment]
Please reopen if this is still an issue.
