### ISSUE TITLE
Selection bar's class can result in undefined and mangling of the 'style-scope' class

### ISSUE THREAD

**Issue by 43081j** [PolymerElements/paper-tabs#89]
I'm unsure if this affects much (probably CSS rules making use of `.style-scope`).

Inside `paper-tabs.html`, [Line 362](https://github.com/PolymerElements/paper-tabs/blob/master/paper-tabs.html#L362), we compute the selection bar class for deciding if it is displayed or not.

```
    _computeSelectionBarClass: function(noBar, alignBottom) {
      if (noBar) {
        return 'hidden';
      } else if (alignBottom) {
        return 'align-bottom';
      }
    },
```

If `noBar` and `alignBottom` are both false, this will return `undefined` and results in `class="undefinedstyle-scope"`, due to the assumption that it always returns here:

```
<div id="selectionBar" class$="[[_computeSelectionBarClass(noBar, alignBottom)]]"
            on-transitionend="_onBarTransitionEnd"></div>
```

**Comment by bicknellr** [comment]
Fixed by #106.
