### ISSUE TITLE
paper-tabs accessibility issues: Windows specific 

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-tabs#9]
Note: Please note that the first rounds of accessibility testing / issue reporting were done using Chrome on Mac with VoiceOver enabled, as well as Chrome on Chrome OS with ChromeVox enabled. This next round was done on the Windows platform, on both Chrome and Firefox with the NVDA screen reader enabled. Once the team addresses the issues across platforms and screen readers, we will also do a final test using Windows and the JAWS screen reader, a heavily used combo that certainly needs to work smoothly. 

Issues: 

Firefox /  NVDA: 
The only issue here is that when I navigate to the start of each tab (on the left) with the keyboard, the first spoken feedback says ""clickable clickable item one"". This repetition of the word clickable only occurs at the start (leftmost region) of each tab, not for items two and three. 
Chrome / NVDA: 
When navigating with the keyboard / NVDA, navigation is fine. However, as mentioned in a previous bug report, when I use the keyboard to activate one of the items, I do not get the visual animation that I get when I use the mouse. This is an inconsistency. and does seem to work on Firefox.

**Comment by notwaldorf** [comment]
I think @cdata might have fixed most of these. @lpalmaro do you mind taking another look, please? Thanks!

**Comment by notwaldorf** [comment]
Closing as this looks like it's been fixed. Please re-open if it's still an issue
